<?php

namespace AppBundle\Repository;
use AppBundle\Factory\CourseMaterialFactory;

/**
 * CourseMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseMaterialRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByFilter($filter = null)
    {
        $query = $this->createQueryBuilder('cm');
        if(!empty($filter))
        {
            $query
                ->where('cm.name like :filter')
                ->setParameter(':filter', "%$filter%");
        }

        return $query->getQuery()->getResult();
    }

    public function getFactory($Doctrine, $Container)
    {
        return new CourseMaterialFactory($this, $Doctrine, $Doctrine->getManager());
    }

}
