<?php

namespace AppBundle\Repository;
use AppBundle\Factory\DiscountFactory;

/**
 * DiscountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscountRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByFilter($filter = null)
    {
        $query = $this->createQueryBuilder('d');
        if(!empty($filter))
        {
            $query
                ->where('d.code like :filter')
                ->setParameter(':filter', "%$filter%");
        }

        return $query->getQuery()->getResult();
    }

    public function getFactory($Doctrine, $Container)
    {
        return new DiscountFactory($this, $Doctrine, $Doctrine->getManager());
    }
}
