<?php

namespace AppBundle\Repository;

use AppBundle\Factory\LinkRelationshipFactory;

/**
 * LinkColumnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRelationshipRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByFilter($filter = null)
    {
        $query = $this->createQueryBuilder('lr')
            ->innerJoin('lr.Navigation', 'n');

        if(!empty($filter))
        {
            $query
                ->where('n.name like :filter or lr.linkText like :filter')
                ->setParameter(':filter', "%$filter%");
        }

        $query->orderBy('lr.sortOrder', 'ASC');

        return $query->getQuery()->getResult();
    }

    public function findByNavigation($filter = null, $_render = 'HTML')
    {
        $query = $this->createQueryBuilder('lr')
            ->innerJoin('lr.Navigation', 'n');

        if(!empty($filter))
        {
            $query
                ->where('n.id = :filter and lr.active = true')
                ->setParameter(':filter', $filter);
        }

        $query->orderBy('lr.sortOrder', 'ASC');

        $result = $query->getQuery()->getResult();

        return $result;

    }

    public function getFactory($Doctrine, $Container)
    {
        return new LinkRelationshipFactory($this, $Doctrine, $Doctrine->getManager());
    }

}
