<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends ApplicationMasterRepository
{
    protected $filter_property = 'name';
    protected $FactoryType = 'AppBundle\Factory\ProductFactory';

    public function prepareFilterByParent($query, $parentid)
    {
        $query
            ->innerJoin('e.configurations', 'c')
            ->andWhere('c.id = :parentid')
            ->setParameter(':parentid', $parentid);
        return $query;
    }


    public function orderByMethod($query, $order_by, $direction)
    {
        if(!empty($order_by))        
            $query->orderBy($order_by, $direction);       
        else
            $query->orderBy('e.sort_order,e.name', 'ASC');

        return $query;
    }
}
