<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends ApplicationMasterRepository
{
    protected $filter_property = 'name';
    protected $FactoryType = 'AppBundle\Factory\ProductFactory';
}
