<?php

namespace AppBundle\Repository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends ApplicationMasterRepository
{
    protected $filter_property = 'reviewer';
    protected $FactoryType = 'AppBundle\Factory\ReviewFactory';
}
