<?php

namespace AppBundle\Repository;
use AppBundle\Factory\UserFactory;

use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Doctrine\ORM\EntityRepository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends ApplicationMasterRepository
{
    protected $filter_property = 'username';
    protected $FactoryType = 'AppBundle\Factory\UserFactory';

    public function findByPhones()
    {
        $query = $this->createQueryBuilder('u');
        $query->where('u.phone IS NOT NULL');

        return $query->getQuery()->getResult();
    }

    public function getFactory($Doctrine, $Container)
    {
        $Manager = $Container->get('app.user_manager');
        $CryptographyService = $Container->get('app.cryptography');
        return new UserFactory($this, $Doctrine,$Manager, $CryptographyService);
    }
}
