# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_AUTHENTICATED: ROLE_USER
        ROLE_ADMIN: ROLE_AUTHENTICATED
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: login
                check_path: login_check
                username_parameter: username
                password_parameter: password
                csrf_token_generator: security.csrf.token_manager
                default_target_path: admin_index
            logout:
                path: logout
                target: login
            anonymous: true
    access_control:
        - { path: ^/admin/login, role: [IS_AUTHENTICATED_ANONYMOUSLY], requires_channel: https }
        - { path: ^/admin, role: [ROLE_ADMIN], requires_channel: https }
        - { path: ^/, role: [IS_AUTHENTICATED_ANONYMOUSLY], requires_channel: https }

