admin_index:
    path: /
    defaults: { _controller: AppBundle:Admin:index }
admin_pricing:
    path: /pricing
    defaults: { _controller: AppBundle:Admin:pricing }
admin_collection:
    path: /collection/{machine}
    defaults: { _controller: AppBundle:Admin:collection, machine: null }

admin_reports_transaction:
    path: /reports/transaction/{machine}
    defaults: { _controller: AppBundle:Admin:reportsTransaction, machine: null }
admin_reports_machine:
    path: /reports/machine
    defaults: { _controller: AppBundle:Admin:reportsMachine }
admin_user_login:
    path: /user/login/{id}
    defaults: { _controller: AppBundle:Admin:userLogin, id: null }
admin_cache:
    path: /cache/clear
    defaults: { _controller: AppBundle:Admin:cache }

login:
    path: /login/{_render}
    defaults: { _controller: AppBundle:Admin:login, _render: 'HTML', machine: null }       
           
login_check:
    path: /login-check
    defaults: { _controller: AppBundle:Admin:loginCheck, _render: 'HTML', _locale: 'en', machine: null }
           
logout:
    path: /logout/{_render}
    defaults: { _controller: AppBundle:Admin:logout, _render: 'HTML', _locale: 'en', machine: null }

admin_reports:
    path: /reports
    defaults: { _controller:AppBundle:Admin:reports, _render: 'HTML', _locale: 'en' }

admin_report_view:
    path: /reports/view
    defaults: { _controller:AppBundle:Admin:reportView, _render: 'HTML', _locale: 'en' }

admin_report_export:
    path: /reports/export
    defaults: { _controller:AppBundle:Admin:reportExport, _render: 'HTML', _locale: 'en' }

admin_report_export_raw:
    path: /reports/export/raw
    defaults: { _controller:AppBundle:Admin:reportExportRaw, _render: 'HTML', _locale: 'en' }

admin_report_summary:
    path: /reports/summary
    defaults: { _controller:AppBundle:Admin:reportSummary, _render:  'HTML', _locale: 'en' }

configuration_settings:
    path: /configuration/settings/{id}
    defaults: { _controller: AppBundle:Admin:configurationSettings, id: null }
    
admin_imports:
    path: /entity/import/{reponame}
    defaults: { _controller:AppBundle:Admin:universalImport, reponame: null }
