root:
    path: /
    defaults: { _controller: AppBundle:Default:root }
    
index:
    path: /start/{user_id}
    defaults: {_controller: AppBundle:Default:index, user_id: null}       
                                                     
search_results:
    path: /search/results/{term}
    defaults: {_controller: AppBundle:Default:searchResults, term: null}       

product_details:
    path: /product/details/{product}
    defaults: {_controller: AppBundle:Default:productDetails, product: null}       

product_reviews:
    path: /product/reviews/{product}
    defaults: {_controller: AppBundle:Default:productReviews, product: null}       

checkout:
    path: /checkout
    defaults: {_controller: AppBudle:Default:checkout }

