AppBundle\Entity\Product:
    type: entity
    repositoryClass: AppBundle\Repository\ProductRepository
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
            created: 
                type: integer
                nullable: false                               
            name:
                type: string
                length: 255
                nullable: false
            image:
                type: text
                nullable: true
            description:
                type: text            
                nullable: true
            price: 
                type: decimal
                scale: 2
                precision: 10
                options:
                    default: 0.0
            tags:
                type: string
                nullable: true
            active:
                type: boolean
                options: 
                    default: true
    oneToMany:
        reviews:
            targetEntity: AppBundle\Entity\Review
            mappedBy: Product
    manyToMany:
        authors:
            targetEntity: AppBundle\Entity\Author
            inversedBy: products
            joinTable:
                name: product_authors
                joinColumns:
                    product_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    author_id:
                        referencedColumnName: id

    lifecycleCallbacks: {  }
