AppBundle\Entity\Review:
    type: entity
    repositoryClass: AppBundle\Repository\ReviewRepository
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
            reviewer:
                type: string
                nullable: false
            created: 
                type: integer
                nullable: false                               
            comment:
                type: text            
                nullable: true
            rating:
                type: decimal
                precision: 10
                scale: 2
                nullable: false
            title:
                type: string
                length: 255
                nullable: true
            help_score:
                type: integer
                nullable: false
                options:
                    default: 0
    manyToOne:
        Product:
            targetEntity: AppBundle\Entity\Product
            inversedBy: reviews
            joinColumn:
                name: product_id
                referencedColumnName:  id

    lifecycleCallbacks: {  }
