AppBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
            created: 
                type: integer
                nullable: false                              
            ip_address:
                type: string
                length: 255
                nullable: true
            external_id:
                type: string
                length: 255
                nullable: false
    oneToMany:
            sessions:
                targetEntity: AppBundle\Entity\Session
                mappedBy: User
                cascade: ['remove']
   
    lifecycleCallbacks: {  }
