AppBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
            created: 
                type: integer
                nullable: false                              
    manyToOne:
            reviews:
                targetEntity: AppBundle\Entity\Review
                mappedBy: User
        
    lifecycleCallbacks: {  }
